#!/usr/bin/env nextflow
/*
========================================================================================
    biocoderep/clade
========================================================================================
    Raw sequencing reads -> six-stage CLADE evidence table.

    CLADE validates candidate compensatory mutations in clonally-reproducing
    bacterial populations, where a variant that merely co-inherited with a
    successful resistant lineage is statistically indistinguishable from one
    that actually compensates. A single structure-corrected association test
    cannot separate them; CLADE requires a candidate to survive six sequential,
    independently-falsifiable checks.

    Documentation: https://github.com/biocoderep/clade
----------------------------------------------------------------------------------------
*/

nextflow.enable.dsl = 2

include { PER_SAMPLE             } from './subworkflows/per_sample'
include { AGGREGATE_AND_VALIDATE } from './subworkflows/aggregate_and_validate'
include { VALIDATE_FROM_MATRIX   } from './subworkflows/validate_from_matrix'
include { DOWNLOAD               } from './modules/download'
include { MULTIQC                } from './modules/multiqc'
include { COLLATE_VERSIONS       } from './modules/collate_versions'

/*
----------------------------------------------------------------------------------------
    HELP / VERSION
----------------------------------------------------------------------------------------
*/

def helpMessage() {
    log.info """
    ============================================================================
     ${workflow.manifest.name} v${workflow.manifest.version}
     ${workflow.manifest.description}
    ============================================================================

    USAGE

      Fully automatic -- reference and raw reads only, everything else
      generated by the pipeline itself:

        nextflow run biocoderep/clade -profile docker \\
            --samplesheet samples.csv \\
            --reference reference.fa \\
            --outdir results

      With a known determinant and/or a curated candidate list (either can
      be given alone; whichever is omitted is still auto-generated):

        nextflow run biocoderep/clade -profile docker \\
            --samplesheet samples.csv \\
            --reference reference.fa \\
            --candidates candidates.csv \\
            --resistance_gene blaOXA-23 \\
            --outdir results

    REQUIRED

      --samplesheet       CSV. Either  sample_id,accession
                          or          sample_id,fastq_1,fastq_2
                          Mixed rows are allowed.
      --reference         Reference genome FASTA (the coordinate system your
                          candidate positions refer to, and everything
                          downstream -- variant calling, AMR/MLST typing,
                          candidate and phenotype auto-discovery -- is
                          derived from this cohort and this reference alone).

    OPTIONAL -- supply either to skip the corresponding auto-discovery step

      --candidates         CSV: name,position -- 1-based positions on the
                           reference. CLADE validates this list; it does not
                           rank it. Omitted, DISCOVER_CANDIDATES generates an
                           unranked, genome-wide list directly from core.vcf
                           -- every core-genome SNP becomes one candidate,
                           and CLADE's own six stages do the separating of
                           signal from clonal noise, not this step.
      --resistance_gene    AMRFinderPlus gene symbol defining the binary
                           phenotype, e.g. blaOXA-23. Omitted,
                           DETECT_RESISTANCE_GENE picks the acquired-AMR gene
                           closest to 50% cohort prevalence (most
                           statistical power for every downstream stage) --
                           a heuristic starting point, reported in full and
                           overridable, not a validated phenotype assignment.
      --auto_gene_min_prevalence / --auto_gene_max_prevalence
                           Eligible prevalence range for auto-detected
                           phenotype genes                [${params.auto_gene_min_prevalence} - ${params.auto_gene_max_prevalence}]
      --auto_candidates_max_missing
                           Max per-site missingness for auto-discovered
                           candidates                     [${params.auto_candidates_max_missing}]

    CLADE STAGE OPTIONS

      --alpha                  Significance threshold                 [${params.alpha}]
      --min_carriers           Minimum carriers to test a candidate   [${params.min_carriers}]
      --max_freq               Above this cohort frequency a candidate
                               is near-fixed and uninformative        [${params.max_freq}]
      --ambiguity_resolution   Fitch tie-breaking: 0 DELTRAN-like,
                               1 ACCTRAN-like                         [${params.ambiguity_resolution}]
      --unique_neighbors       Enforce 1:1 matching in Stage 5        [${params.unique_neighbors}]
      --stage1_results         Use externally computed Stage 1 results
                               (e.g. pyseer output) instead of the
                               built-in Firth fit                     [${params.stage1_results}]
      --stage6                 JSON of manual corroboration findings  [${params.stage6}]

    OUTPUT

      --outdir                 Results directory                      [${params.outdir}]
      --publish_dir_mode       copy | symlink | link                  [${params.publish_dir_mode}]
      --save_trimmed           Keep trimmed FASTQs                    [${params.save_trimmed}]
      --save_assemblies        Keep assemblies                        [${params.save_assemblies}]
      --save_snippy_dirs       Keep per-sample Snippy dirs (large)    [${params.save_snippy_dirs}]

    RESOURCES  (ceilings for THIS machine; requests are capped to them)

      --max_cpus               [${params.max_cpus}]
      --max_memory             [${params.max_memory}]
      --max_time               [${params.max_time}]

    PROFILES

      docker, singularity, apptainer, podman   containerised (recommended)
      conda, mamba                             conda fallback
      test                                     tiny inputs, for -stub-run
      local, slurm                             executor presets

    A five-second wiring check, no tools or data required:

      nextflow run main.nf -profile test,docker -stub-run

    """.stripIndent()
}

/*
----------------------------------------------------------------------------------------
    INPUT VALIDATION
----------------------------------------------------------------------------------------
*/

def validateParams() {
    def errors = []

    if (!params.samplesheet)     errors << "--samplesheet is required"
    if (!params.reference)       errors << "--reference is required"
    // --candidates and --resistance_gene are now OPTIONAL: omitted, the
    // pipeline generates both itself -- an unranked, genome-wide candidate
    // list from core.vcf (DISCOVER_CANDIDATES), and a phenotype gene detected
    // from the cohort's own AMRFinderPlus calls (DETECT_RESISTANCE_GENE).
    // A user who already knows which determinant and which candidates they
    // want can still supply either or both to skip the corresponding
    // auto-discovery step.

    // Fail on a missing input file here, at second zero, rather than after the
    // cohort has already been downloaded and assembled.
    [ 'samplesheet': params.samplesheet,
      'reference'  : params.reference,
      'candidates' : params.candidates ].each { name, value ->
        if (value && !file(value).exists()) errors << "--${name} does not exist: ${value}"
    }

    if (params.alpha <= 0 || params.alpha >= 1)  errors << "--alpha must be between 0 and 1 (got ${params.alpha})"
    if (params.max_freq <= 0 || params.max_freq > 1) errors << "--max_freq must be in (0,1] (got ${params.max_freq})"
    if (params.min_carriers < 1)                 errors << "--min_carriers must be >= 1 (got ${params.min_carriers})"
    if (!(params.ambiguity_resolution in [0, 1])) errors << "--ambiguity_resolution must be 0 or 1 (got ${params.ambiguity_resolution})"
    if (!(params.publish_dir_mode in ['copy','symlink','link','rellink','move'])) {
        errors << "--publish_dir_mode '${params.publish_dir_mode}' is not valid"
    }

    if (errors) {
        log.error "Parameter validation failed:\n  - " + errors.join("\n  - ") +
                  "\n\nRun with --help for usage."
        System.exit(1)
    }
}

def validateMatrixParams() {
    def errors = []
    def required = [
        'matrix_genotypes': params.matrix_genotypes, 'matrix_phenotype': params.matrix_phenotype,
        'matrix_lineages' : params.matrix_lineages,  'matrix_candidates': params.matrix_candidates,
        'matrix_tree'     : params.matrix_tree,      'matrix_distances': params.matrix_distances,
    ]
    required.each { name, value ->
        if (!value) errors << "--${name} is required with --from_matrix"
        else if (!file(value).exists()) errors << "--${name} does not exist: ${value}"
    }
    if (params.alpha <= 0 || params.alpha >= 1)  errors << "--alpha must be between 0 and 1 (got ${params.alpha})"
    if (params.max_freq <= 0 || params.max_freq > 1) errors << "--max_freq must be in (0,1] (got ${params.max_freq})"
    if (params.min_carriers < 1)                 errors << "--min_carriers must be >= 1 (got ${params.min_carriers})"
    if (!(params.ambiguity_resolution in [0, 1])) errors << "--ambiguity_resolution must be 0 or 1 (got ${params.ambiguity_resolution})"
    if (errors) {
        log.error "Parameter validation failed:\n  - " + errors.join("\n  - ") + "\n\nRun with --help for usage."
        System.exit(1)
    }
}

def summaryLog() {
    log.info """
    ----------------------------------------------------------------------------
     ${workflow.manifest.name} v${workflow.manifest.version}
    ----------------------------------------------------------------------------
     samplesheet      : ${params.samplesheet}
     reference        : ${params.reference}
     candidates       : ${params.candidates ?: '(auto-discover from core.vcf)'}
     resistance gene  : ${params.resistance_gene ?: '(auto-detect from AMRFinderPlus calls)'}
     outdir           : ${params.outdir}
     profile          : ${workflow.profile}
     container engine : ${workflow.containerEngine ?: 'none (conda or local)'}
     max cpus/mem/time: ${params.max_cpus} / ${params.max_memory} / ${params.max_time}
     Nextflow         : ${workflow.nextflow.version}
     run name         : ${workflow.runName}
    ----------------------------------------------------------------------------
    """.stripIndent()
}

/*
----------------------------------------------------------------------------------------
    MAIN WORKFLOW
----------------------------------------------------------------------------------------
*/

workflow {

    if (params.help)    { helpMessage(); System.exit(0) }
    if (params.version) { log.info "${workflow.manifest.name} v${workflow.manifest.version}"; System.exit(0) }

    if (params.from_matrix) {
        /*
         * Skip genome processing entirely: genotype matrix, phenotype,
         * lineages, phylogeny and distance matrix are already extracted.
         * This is the entry point this project's real case-study analysis
         * actually used -- validated by hand against these same files
         * before this subworkflow existed, so a result that disagrees with
         * that hand-run is a bug in the pipeline, not a new finding.
         */
        validateMatrixParams()
        log.info "Running in --from_matrix mode: genome processing skipped."

        // Wrapped as value channels, not passed as bare file() objects: a bare
        // Path fed into a subworkflow's splitCsv() there returns a plain
        // Groovy List, not a Channel, and List has no .map() -- a real error
        // this run surfaced (the raw-reads path avoids it because ch_candidates
        // is already Channel.value(file(...)) before AGGREGATE_AND_VALIDATE
        // ever sees it).
        VALIDATE_FROM_MATRIX(
            Channel.value(file(params.matrix_genotypes, checkIfExists: true)),
            Channel.value(file(params.matrix_phenotype, checkIfExists: true)),
            Channel.value(file(params.matrix_lineages,  checkIfExists: true)),
            Channel.value(file(params.matrix_candidates, checkIfExists: true)),
            Channel.value(file(params.matrix_tree,      checkIfExists: true)),
            Channel.value(file(params.matrix_distances, checkIfExists: true)),
        )
        COLLATE_VERSIONS(VALIDATE_FROM_MATRIX.out.versions.unique().collectFile(name: 'collated_versions.yml'))
        return
    }

    validateParams()
    summaryLog()

    ch_reference  = Channel.value(file(params.reference,  checkIfExists: true))
    ch_versions   = Channel.empty()

    /*
     * A samplesheet row is either an SRA accession to fetch or a pair of local
     * FASTQs. Both are supported in the same sheet: a cohort assembled from
     * public data plus unreleased local isolates is the normal case, not an
     * edge case.
     */
    ch_samplesheet = Channel.fromPath(params.samplesheet, checkIfExists: true)
        .splitCsv(header: true)
        .map { row ->
            if (!row.sample_id?.trim() && !row.accession?.trim()) {
                error "Samplesheet row has neither sample_id nor accession: ${row}"
            }
            row
        }

    ch_to_download = ch_samplesheet.filter { it.accession?.trim() }.map { it.accession.trim() }
    ch_local_reads = ch_samplesheet
        .filter { it.fastq_1?.trim() }
        .map { row -> tuple(row.sample_id.trim(),
                            file(row.fastq_1.trim(), checkIfExists: true),
                            file(row.fastq_2.trim(), checkIfExists: true)) }

    DOWNLOAD(ch_to_download)
    ch_versions = ch_versions.mix(DOWNLOAD.out.versions.first().ifEmpty([]))

    ch_reads = DOWNLOAD.out.reads.mix(ch_local_reads)

    PER_SAMPLE(ch_reads, ch_reference)
    ch_versions = ch_versions.mix(PER_SAMPLE.out.versions)

    AGGREGATE_AND_VALIDATE(
        PER_SAMPLE.out.snippy_dirs,
        PER_SAMPLE.out.amrfinder,
        PER_SAMPLE.out.mlst,
        ch_reference,
        params.candidates,
        params.resistance_gene
    )
    ch_versions = ch_versions.mix(AGGREGATE_AND_VALIDATE.out.versions)

    if (!params.skip_multiqc) {
        MULTIQC(PER_SAMPLE.out.qc.collect().ifEmpty([]))
        ch_versions = ch_versions.mix(MULTIQC.out.versions)
    }

    COLLATE_VERSIONS(ch_versions.unique().collectFile(name: 'collated_versions.yml'))
}
